# cronograma_data.py — Ementa de Segurança da Informação
# AGENTE D (conteúdo)

OBJETIVOS = {
    "geral": "Generalista",
    "red": "Red Team / Pentest",
    "blue": "Blue Team / Defesa",
    "appsec": "AppSec / Bug Bounty",
}

MODULOS = [
    {
        "slug": "fundamentos-redes",
        "titulo": "Fundamentos de Redes",
        "icone": "network",
        "descricao": "Compreender a arquitetura de redes, modelos de camadas e protocolos fundamentais para comunicação segura.",
        "ordem": 1,
        "objetivos": ["geral", "red", "blue"],
        "topicos": [
            {
                "slug": "modelo-osi-tcpip",
                "titulo": "Modelo OSI e TCP/IP",
                "descricao": "Aprenda as 7 camadas OSI e como o modelo TCP/IP simplifica a comunicação em redes modernas.",
                "nivel": "Iniciante",
                "palavras_chave": ["camadas", "encapsulamento", "protocolos"],
            },
            {
                "slug": "protocolo-tcp-udp",
                "titulo": "Protocolos TCP e UDP",
                "descricao": "Diferencie protocolos orientados a conexão (TCP) e sem conexão (UDP), entendendo quando cada um é usado.",
                "nivel": "Iniciante",
                "palavras_chave": ["conexão", "confiabilidade", "latência"],
            },
            {
                "slug": "enderecamento-ip",
                "titulo": "Endereçamento IP e Subnetting",
                "descricao": "Compreenda IPv4 e IPv6, classes de rede, máscaras de sub-rede e como segmentar redes logicamente.",
                "nivel": "Intermediário",
                "palavras_chave": ["CIDR", "máscara", "routing"],
            },
            {
                "slug": "dns-http-https",
                "titulo": "DNS, HTTP e HTTPS",
                "descricao": "Entenda a resolução de nomes (DNS) e os protocolos de aplicação HTTP/HTTPS que sustentam a Web.",
                "nivel": "Intermediário",
                "palavras_chave": ["resolução", "certificado", "TLS"],
            },
            {
                "slug": "firewall-nat",
                "titulo": "Firewall e NAT",
                "descricao": "Aprenda como firewalls filtram tráfego e NAT traduz endereços para conectar redes privadas à pública.",
                "nivel": "Intermediário",
                "palavras_chave": ["filtragem", "stateful", "DNAT"],
            },
            {
                "slug": "analise-trafego-wireshark",
                "titulo": "Análise de Tráfego com Wireshark",
                "descricao": "Use ferramentas de captura de pacotes para monitorar e analisar comunicações em tempo real.",
                "nivel": "Avançado",
                "palavras_chave": ["captura", "dissector", "filtro"],
            },
        ],
    },
    {
        "slug": "linux-seguranca",
        "titulo": "Linux para Segurança",
        "icone": "terminal",
        "descricao": "Domine o sistema operacional Linux, seus mecanismos de segurança e comandos essenciais para profissionais de cibersegurança.",
        "ordem": 2,
        "objetivos": ["geral", "red", "blue"],
        "topicos": [
            {
                "slug": "shell-bash-scripting",
                "titulo": "Shell Bash e Scripting",
                "descricao": "Automatize tarefas com scripts Bash, manipule variáveis e entenda fluxo de controle.",
                "nivel": "Iniciante",
                "palavras_chave": ["variáveis", "loops", "funções"],
            },
            {
                "slug": "permissoes-usuarios-grupos",
                "titulo": "Permissões, Usuários e Grupos",
                "descricao": "Gerencie permissões de arquivo (chmod, chown), crie usuários e grupos, e controle acesso com sudo.",
                "nivel": "Iniciante",
                "palavras_chave": ["rwx", "uid", "gid"],
            },
            {
                "slug": "processos-servicos-systemd",
                "titulo": "Processos, Serviços e Systemd",
                "descricao": "Monitore processos em execução, controle serviços com systemd e gerencie recursos do sistema.",
                "nivel": "Intermediário",
                "palavras_chave": ["daemon", "pid", "systemctl"],
            },
            {
                "slug": "rede-linux-interfaces",
                "titulo": "Rede no Linux: Interfaces e Configuração",
                "descricao": "Configure interfaces de rede, roteamento e DNS no Linux para conectividade segura.",
                "nivel": "Intermediário",
                "palavras_chave": ["ifconfig", "ip", "route"],
            },
            {
                "slug": "auditoria-logs-linux",
                "titulo": "Auditoria e Logs no Linux",
                "descricao": "Use ferramentas como auditd e syslog para rastrear atividades e detectar anomalias.",
                "nivel": "Avançado",
                "palavras_chave": ["auditd", "syslog", "monitoramento"],
            },
            {
                "slug": "containers-docker-basico",
                "titulo": "Containers e Docker Básico",
                "descricao": "Entenda isolamento de processos, imagens Docker e como containerização afeta a segurança.",
                "nivel": "Avançado",
                "palavras_chave": ["container", "imagem", "isolamento"],
            },
        ],
    },
    {
        "slug": "windows-active-directory",
        "titulo": "Windows e Active Directory (Conceitos)",
        "icone": "server",
        "descricao": "Compreenda arquitetura Windows, autenticação e o papel central do Active Directory em empresas.",
        "ordem": 3,
        "objetivos": ["geral", "red", "blue"],
        "topicos": [
            {
                "slug": "arquitetura-windows-seguranca",
                "titulo": "Arquitetura do Windows e Segurança",
                "descricao": "Entenda componentes-chave do Windows: kernel, privilégios, UAC e como proteger credenciais.",
                "nivel": "Intermediário",
                "palavras_chave": ["kernel", "UAC", "privilégio"],
            },
            {
                "slug": "active-directory-conceitos",
                "titulo": "Active Directory: Conceitos Fundamentais",
                "descricao": "Aprenda a estrutura de AD: domínios, árvores, florestas, OUs e como o AD centraliza identidades.",
                "nivel": "Intermediário",
                "palavras_chave": ["domínio", "LDAP", "Kerberos"],
            },
            {
                "slug": "autenticacao-kerberos",
                "titulo": "Autenticação Kerberos",
                "descricao": "Compreenda o protocolo Kerberos: tickets, TGT e como evitar ataques como pass-the-ticket.",
                "nivel": "Avançado",
                "palavras_chave": ["ticket", "TGT", "autenticação"],
            },
            {
                "slug": "grupo-politica-gpo",
                "titulo": "Grupo de Política (GPO)",
                "descricao": "Use GPOs para enforçar configurações de segurança em massa em ambientes Windows/AD.",
                "nivel": "Avançado",
                "palavras_chave": ["GPO", "SYSVOL", "aplicação"],
            },
            {
                "slug": "windows-defender-edr",
                "titulo": "Windows Defender e EDR",
                "descricao": "Conheça ferramentas de proteção nativa Windows e detecção/resposta a ameaças (EDR).",
                "nivel": "Intermediário",
                "palavras_chave": ["antimalware", "detecção", "EDR"],
            },
        ],
    },
    {
        "slug": "criptografia",
        "titulo": "Criptografia",
        "icone": "key",
        "descricao": "Domine algoritmos de criptografia simétrica, assimétrica, hash e sua aplicação em segurança de dados.",
        "ordem": 4,
        "objetivos": ["geral", "red", "blue", "appsec"],
        "topicos": [
            {
                "slug": "simetrica-aes-des",
                "titulo": "Criptografia Simétrica: AES e DES",
                "descricao": "Aprenda como DES (obsoleto) e AES funcionam, e por que AES-256 é recomendado para dados sensíveis.",
                "nivel": "Intermediário",
                "palavras_chave": ["chave", "blocos", "modos"],
            },
            {
                "slug": "asimetrica-rsa-ecc",
                "titulo": "Criptografia Assimétrica: RSA e ECC",
                "descricao": "Entenda como chaves públicas/privadas funcionam em RSA e ECC, e seus usos em assinatura digital.",
                "nivel": "Intermediário",
                "palavras_chave": ["chave pública", "privada", "fatoração"],
            },
            {
                "slug": "funcoes-hash-md5-sha",
                "titulo": "Funções Hash: MD5, SHA e BLAKE",
                "descricao": "Compreenda hash criptográfico, colisões e por que MD5 é quebrado; use SHA-256 ou BLAKE2.",
                "nivel": "Intermediário",
                "palavras_chave": ["digest", "colisão", "integridade"],
            },
            {
                "slug": "assinatura-digital-certificados",
                "titulo": "Assinatura Digital e Certificados X.509",
                "descricao": "Aprenda como assinaturas digitais garantem autenticidade e como certificados vinculam identidades a chaves públicas.",
                "nivel": "Avançado",
                "palavras_chave": ["certificado", "CA", "PKI"],
            },
            {
                "slug": "tls-ssl-seguranca-web",
                "titulo": "TLS/SSL e Segurança Web",
                "descricao": "Entenda o protocolo TLS: handshake, cipher suites, perfect forward secrecy e como detectar man-in-the-middle.",
                "nivel": "Avançado",
                "palavras_chave": ["TLS", "cipher", "certificado"],
            },
            {
                "slug": "esteganografia-conceitos",
                "titulo": "Esteganografia e Steganálise",
                "descricao": "Aprenda a ocultar dados em imagens/áudio e como detectar mensagens escondidas.",
                "nivel": "Avançado",
                "palavras_chave": ["ocultação", "detecção", "payload"],
            },
        ],
    },
    {
        "slug": "seguranca-web-owasp",
        "titulo": "Segurança Web (OWASP Top 10)",
        "icone": "globe",
        "descricao": "Identifique e mitigue as 10 vulnerabilidades web mais críticas segundo a OWASP.",
        "ordem": 5,
        "objetivos": ["geral", "red", "blue", "appsec"],
        "topicos": [
            {
                "slug": "injecao-sql-xss",
                "titulo": "Injeção SQL e XSS",
                "descricao": "Entenda como ataques de injeção (SQL, XSS) funcionam e como validar/sanitizar entrada de usuário.",
                "nivel": "Intermediário",
                "palavras_chave": ["injeção", "sanitização", "escape"],
            },
            {
                "slug": "autenticacao-sessao",
                "titulo": "Falhas de Autenticação e Gerenciamento de Sessão",
                "descricao": "Compreenda ataques a senhas fracas, reutilização de sessão, brute force e defesas adequadas.",
                "nivel": "Intermediário",
                "palavras_chave": ["sessão", "cookie", "token"],
            },
            {
                "slug": "controle-acesso",
                "titulo": "Controle de Acesso Quebrado",
                "descricao": "Aprenda sobre escalação de privilégio, IDOR (Insecure Direct Object Reference) e privilege escalation.",
                "nivel": "Intermediário",
                "palavras_chave": ["IDOR", "privilégio", "autorização"],
            },
            {
                "slug": "criptografia-dados-transito",
                "titulo": "Segurança de Dados em Trânsito e em Repouso",
                "descricao": "Proteja dados usando TLS, criptografia em repouso e gestão segura de chaves.",
                "nivel": "Intermediário",
                "palavras_chave": ["TLS", "criptografia", "chave"],
            },
            {
                "slug": "xxe-desserializacao",
                "titulo": "XXE e Desserialização Insegura",
                "descricao": "Entenda ataques XML External Entity e riscos de desserializar objetos não confiáveis.",
                "nivel": "Avançado",
                "palavras_chave": ["XML", "desserialização", "objeto"],
            },
            {
                "slug": "csp-cors-seguranca-navegador",
                "titulo": "CSP, CORS e Segurança do Navegador",
                "descricao": "Aprenda sobre políticas de segurança de conteúdo, compartilhamento cross-origin e proteções do navegador.",
                "nivel": "Avançado",
                "palavras_chave": ["CSP", "CORS", "política"],
            },
            {
                "slug": "rate-limiting-dos",
                "titulo": "Rate Limiting e Proteção contra DoS",
                "descricao": "Implemente rate limiting e WAF para mitigar ataques de negação de serviço.",
                "nivel": "Avançado",
                "palavras_chave": ["rate limit", "DoS", "WAF"],
            },
        ],
    },
    {
        "slug": "seguranca-apis",
        "titulo": "Segurança de APIs",
        "icone": "code",
        "descricao": "Proteja APIs REST e GraphQL contra vulnerabilidades, autenticação fraca e exposição de dados.",
        "ordem": 6,
        "objetivos": ["geral", "red", "blue", "appsec"],
        "topicos": [
            {
                "slug": "autenticacao-api-oauth-jwt",
                "titulo": "Autenticação de API: OAuth 2.0 e JWT",
                "descricao": "Aprenda OAuth 2.0 para autorização delegada e JWT para tokens stateless seguros.",
                "nivel": "Intermediário",
                "palavras_chave": ["OAuth", "JWT", "token"],
            },
            {
                "slug": "rate-limiting-throttling-api",
                "titulo": "Rate Limiting e Throttling em APIs",
                "descricao": "Implemente rate limiting para evitar abuso, scrapers e ataques de força bruta em APIs.",
                "nivel": "Intermediário",
                "palavras_chave": ["rate limit", "quota", "throttle"],
            },
            {
                "slug": "versionamento-deprecacao-api",
                "titulo": "Versionamento e Deprecação de APIs",
                "descricao": "Gerencie versões de API, comunique mudanças quebradas e retire endpoints legados com segurança.",
                "nivel": "Intermediário",
                "palavras_chave": ["versão", "deprecação", "compatibilidade"],
            },
            {
                "slug": "graphql-seguranca",
                "titulo": "GraphQL e Segurança",
                "descricao": "Entenda vulnerabilidades específicas de GraphQL: query complexity, introspection e batching.",
                "nivel": "Avançado",
                "palavras_chave": ["query", "introspection", "complexidade"],
            },
            {
                "slug": "validacao-esquema-api",
                "titulo": "Validação de Esquema e Input",
                "descricao": "Valide rigidamente entrada de usuário em APIs, use schemas e proteja contra injeções.",
                "nivel": "Intermediário",
                "palavras_chave": ["validação", "schema", "sanitização"],
            },
            {
                "slug": "documentacao-segura-api",
                "titulo": "Documentação Segura de APIs",
                "descricao": "Documente APIs sem expor informações sensíveis, hide endpoints internos e proteja swagger/openapi.",
                "nivel": "Intermediário",
                "palavras_chave": ["documentação", "swagger", "exposição"],
            },
        ],
    },
    {
        "slug": "reconhecimento-osint",
        "titulo": "Reconhecimento e OSINT",
        "icone": "search",
        "descricao": "Reúna inteligência de fontes abertas para mapeamento de alvos, sem invaso técnica.",
        "ordem": 7,
        "objetivos": ["geral", "red"],
        "topicos": [
            {
                "slug": "osint-passive-information-gathering",
                "titulo": "OSINT Passivo e Information Gathering",
                "descricao": "Reúna dados públicos: DNS, WHOIS, domínios registrados, vazamentos de credenciais.",
                "nivel": "Iniciante",
                "palavras_chave": ["OSINT", "WHOIS", "DNS"],
            },
            {
                "slug": "reconhecimento-web-footprinting",
                "titulo": "Reconhecimento Web e Footprinting",
                "descricao": "Mapeie infraestrutura web: servidores, tecnologias, headers HTTP e diretórios públicos.",
                "nivel": "Intermediário",
                "palavras_chave": ["footprint", "banner", "diretório"],
            },
            {
                "slug": "enumeracao-dns-subdominios",
                "titulo": "Enumeração de DNS e Subdomínios",
                "descricao": "Descubra subdomínios e registros DNS para identificar todos os ativos de um alvo.",
                "nivel": "Intermediário",
                "palavras_chave": ["DNS", "subdomínio", "wildcard"],
            },
            {
                "slug": "vazamento-dados-breachdatabase",
                "titulo": "Vazamento de Dados e Breach Databases",
                "descricao": "Pesquise bases de dados públicas de vazamentos para avaliar exposição de credenciais.",
                "nivel": "Intermediário",
                "palavras_chave": ["breach", "credencial", "vazamento"],
            },
            {
                "slug": "reconhecimento-social-engenharia",
                "titulo": "Engenharia Social e Reconhecimento",
                "descricao": "Entenda técnicas de manipulação humana e como se defender contra ataques de engenharia social.",
                "nivel": "Intermediário",
                "palavras_chave": ["phishing", "pretexting", "manipulação"],
            },
            {
                "slug": "framework-mitre-att-ck",
                "titulo": "Framework MITRE ATT&CK",
                "descricao": "Use a taxonomia MITRE para mapear reconhecimento, técnicas e táticas adversárias.",
                "nivel": "Avançado",
                "palavras_chave": ["MITRE", "tática", "técnica"],
            },
        ],
    },
    {
        "slug": "analise-vulnerabilidades-pentest",
        "titulo": "Análise de Vulnerabilidades e Pentest",
        "icone": "bug",
        "descricao": "Metodologia, escopo, ética e relatórios de testes de penetração profissionais.",
        "ordem": 8,
        "objetivos": ["geral", "red", "blue"],
        "topicos": [
            {
                "slug": "metodologia-pentest-fases",
                "titulo": "Metodologia Pentest: Fases e Escopo",
                "descricao": "Compreenda as 5 fases: reconhecimento, scanning, enumeração, exploração e pós-exploração.",
                "nivel": "Intermediário",
                "palavras_chave": ["metodologia", "escopo", "fase"],
            },
            {
                "slug": "scanning-enumeracao-ferramentas",
                "titulo": "Scanning e Enumeração com Ferramentas",
                "descricao": "Use Nmap, Masscan, nessus para descobrir hosts, portas, versões de serviço.",
                "nivel": "Intermediário",
                "palavras_chave": ["Nmap", "scanning", "serviço"],
            },
            {
                "slug": "classificacao-vulnerabilidades-cvss",
                "titulo": "Classificação de Vulnerabilidades (CVSS)",
                "descricao": "Use CVSS para avaliar severidade de vulnerabilidades de forma padronizada.",
                "nivel": "Intermediário",
                "palavras_chave": ["CVSS", "severidade", "score"],
            },
            {
                "slug": "etica-pentest-acordo-legal",
                "titulo": "Ética, Legalidade e ROE do Pentest",
                "descricao": "Entenda limitações legais, contrato de autorização, Rules of Engagement e responsabilidade.",
                "nivel": "Intermediário",
                "palavras_chave": ["ROE", "contrato", "legalidade"],
            },
            {
                "slug": "relatorio-pentest-comunicacao",
                "titulo": "Relatório de Pentest e Comunicação",
                "descricao": "Escreva relatórios técnicos e executivos claros, apresente achados e recomendações.",
                "nivel": "Avançado",
                "palavras_chave": ["relatório", "achado", "recomendação"],
            },
            {
                "slug": "retesting-validacao-remediacao",
                "titulo": "Retesting e Validação de Remediação",
                "descricao": "Valide que correções de vulnerabilidades foram efetivas e não introduziram novos riscos.",
                "nivel": "Avançado",
                "palavras_chave": ["validação", "remediação", "reteste"],
            },
        ],
    },
    {
        "slug": "blue-team-monitoramento-siem",
        "titulo": "Blue Team: Monitoramento, Logs e SIEM",
        "icone": "eye",
        "descricao": "Configure monitoramento, centralize logs e use SIEM para detectar ameaças em tempo real.",
        "ordem": 9,
        "objetivos": ["geral", "blue"],
        "topicos": [
            {
                "slug": "logs-centralizacao-siem",
                "titulo": "Centralização de Logs e SIEM",
                "descricao": "Colete logs de múltiplas fontes, normalize e analise com Splunk, ELK, ArcSight.",
                "nivel": "Intermediário",
                "palavras_chave": ["SIEM", "log", "agregação"],
            },
            {
                "slug": "regras-deteccao-alertas",
                "titulo": "Regras de Detecção e Alertas",
                "descricao": "Crie regras para identificar padrões de ataque, ajuste sensibilidade para reduzir falsos positivos.",
                "nivel": "Intermediário",
                "palavras_chave": ["regra", "padrão", "alerta"],
            },
            {
                "slug": "ips-ids-honeypot",
                "titulo": "IPS/IDS e Honeypots",
                "descricao": "Implemente sistemas de prevenção/detecção de intrusão e honeypots para isolar atacantes.",
                "nivel": "Intermediário",
                "palavras_chave": ["IDS", "IPS", "honeypot"],
            },
            {
                "slug": "analise-comportamento-usuario",
                "titulo": "Análise de Comportamento de Usuário (UEBA)",
                "descricao": "Use UEBA para detectar atividades anormais de usuários, comprometimento de contas.",
                "nivel": "Avançado",
                "palavras_chave": ["UEBA", "comportamento", "anomalia"],
            },
            {
                "slug": "correlacao-eventos-timeline",
                "titulo": "Correlação de Eventos e Timeline",
                "descricao": "Correlacione eventos de múltiplas fontes, monte timelines de incidentes.",
                "nivel": "Avançado",
                "palavras_chave": ["correlação", "timeline", "evento"],
            },
            {
                "slug": "threat-intelligence-indicadores",
                "titulo": "Threat Intelligence e Indicadores de Compromisso",
                "descricao": "Use feeds de threat intelligence, IoCs (IPs, hashes) para detectar ameaças conhecidas.",
                "nivel": "Avançado",
                "palavras_chave": ["IoC", "threat intel", "indicador"],
            },
        ],
    },
    {
        "slug": "resposta-incidentes-forense",
        "titulo": "Resposta a Incidentes e Forense",
        "icone": "alert",
        "descricao": "Responda a incidentes de segurança, investigue compromissos e preserve evidência digital.",
        "ordem": 10,
        "objetivos": ["geral", "blue"],
        "topicos": [
            {
                "slug": "plano-resposta-incidentes",
                "titulo": "Plano de Resposta a Incidentes (IRP)",
                "descricao": "Estruture um Incident Response Plan: papéis, escalação, comunicação, recuperação.",
                "nivel": "Intermediário",
                "palavras_chave": ["IRP", "plano", "escala"],
            },
            {
                "slug": "deteccao-classificacao-incidente",
                "titulo": "Detecção e Classificação de Incidentes",
                "descricao": "Identifique incidentes, classifique severidade e ative equipes apropriadas.",
                "nivel": "Intermediário",
                "palavras_chave": ["detecção", "classificação", "severidade"],
            },
            {
                "slug": "contencao-erradicacao-recuperacao",
                "titulo": "Contenção, Erradicação e Recuperação",
                "descricao": "Isole sistemas comprometidos, remova malware e recupere operações normais.",
                "nivel": "Intermediário",
                "palavras_chave": ["contenção", "remediação", "recuperação"],
            },
            {
                "slug": "forense-digital-coleta-evidencia",
                "titulo": "Forense Digital e Coleta de Evidência",
                "descricao": "Colete, preserve e documente evidência de incidente para investigação e possível legal.",
                "nivel": "Avançado",
                "palavras_chave": ["forense", "evidência", "cadeia"],
            },
            {
                "slug": "analise-memoria-disco",
                "titulo": "Análise de Memória e Disco",
                "descricao": "Use ferramentas como volatility para analyar dumps de memória e sistemas de arquivo.",
                "nivel": "Avançado",
                "palavras_chave": ["dump", "volatility", "análise"],
            },
            {
                "slug": "lissoes-aprendidas-mejora",
                "titulo": "Lições Aprendidas e Melhoria Contínua",
                "descricao": "Documente incidentes, analise root cause e implemente melhorias preventivas.",
                "nivel": "Avançado",
                "palavras_chave": ["root cause", "melhoria", "lição"],
            },
        ],
    },
    {
        "slug": "analise-malware",
        "titulo": "Análise de Malware (Conceitos)",
        "icone": "file",
        "descricao": "Compreenda tipos de malware, técnicas de ofuscação e como analisar amostras com segurança.",
        "ordem": 11,
        "objetivos": ["geral", "blue"],
        "topicos": [
            {
                "slug": "tipos-malware-virus-worm-trojan",
                "titulo": "Tipos de Malware: Vírus, Worm, Trojan",
                "descricao": "Aprenda características e propagação de vírus, worms, trojans, ransomware e spyware.",
                "nivel": "Iniciante",
                "palavras_chave": ["vírus", "propagação", "dano"],
            },
            {
                "slug": "ofuscacao-packers-criptografia",
                "titulo": "Ofuscação, Packers e Criptografia",
                "descricao": "Entenda técnicas para esconder código malicioso: packers, criptografia, anti-análise.",
                "nivel": "Intermediário",
                "palavras_chave": ["packer", "ofuscação", "anti-análise"],
            },
            {
                "slug": "analise-dinamica-estatica",
                "titulo": "Análise Dinâmica e Estática",
                "descricao": "Analise malware em sandbox (dinâmica) e disassemble código (estática) para entender comportamento.",
                "nivel": "Intermediário",
                "palavras_chave": ["sandbox", "disassembly", "comportamento"],
            },
            {
                "slug": "indicadores-compromiso-ioc",
                "titulo": "Indicadores de Compromisso (IoC)",
                "descricao": "Identifique IoCs de malware: hashes, IPs de C2, domínios, URLs para detecção.",
                "nivel": "Intermediário",
                "palavras_chave": ["IoC", "hash", "C2"],
            },
            {
                "slug": "ransomware-encriptacao-defesa",
                "titulo": "Ransomware: Encriptação e Defesa",
                "descricao": "Compreenda ransomware moderno: criptografia, pagamento, backup e recuperação.",
                "nivel": "Avançado",
                "palavras_chave": ["encriptação", "backup", "recuperação"],
            },
            {
                "slug": "apt-persist-c2-comunicacao",
                "titulo": "APT, Persistência e Comando & Controle",
                "descricao": "Estudar ataques dirigidos (APT): técnicas de persistência, comunicação C2 e exfiltração.",
                "nivel": "Avançado",
                "palavras_chave": ["APT", "persistência", "C2"],
            },
        ],
    },
    {
        "slug": "cloud-containers",
        "titulo": "Cloud e Containers",
        "icone": "cloud",
        "descricao": "Segurança em ambientes cloud (AWS, Azure, GCP) e containerização com Kubernetes.",
        "ordem": 12,
        "objetivos": ["geral", "blue"],
        "topicos": [
            {
                "slug": "cloud-modelos-responsabilidade",
                "titulo": "Modelos Cloud e Responsabilidade Compartilhada",
                "descricao": "Entenda IaaS, PaaS, SaaS e quem é responsável por quê em cada modelo.",
                "nivel": "Intermediário",
                "palavras_chave": ["IaaS", "PaaS", "responsabilidade"],
            },
            {
                "slug": "identidade-acesso-cloud-iam",
                "titulo": "Identidade e Acesso em Cloud (IAM)",
                "descricao": "Configure políticas IAM, papéis, grupos em AWS, Azure, GCP com least privilege.",
                "nivel": "Intermediário",
                "palavras_chave": ["IAM", "política", "privilégio"],
            },
            {
                "slug": "seguranca-armazenamento-cloud",
                "titulo": "Segurança de Armazenamento em Cloud",
                "descricao": "Proteja buckets S3, containers Azure, criptografia em repouso e acesso.",
                "nivel": "Intermediário",
                "palavras_chave": ["bucket", "acesso", "criptografia"],
            },
            {
                "slug": "kubernetes-orquestracao-containers",
                "titulo": "Kubernetes: Orquestração de Containers",
                "descricao": "Compreenda Kubernetes: pods, services, secrets management e rede segura.",
                "nivel": "Avançado",
                "palavras_chave": ["pod", "service", "secret"],
            },
            {
                "slug": "seguranca-imagem-docker-sbom",
                "titulo": "Segurança de Imagem Docker e SBOM",
                "descricao": "Escaneie imagens Docker por vulnerabilidades, crie SBOM (Software Bill of Materials).",
                "nivel": "Avançado",
                "palavras_chave": ["imagem", "vulnerabilidade", "SBOM"],
            },
            {
                "slug": "serverless-funcoes-aws-lambda",
                "titulo": "Serverless: Funções e AWS Lambda",
                "descricao": "Segurança em arquiteturas serverless: gestão de secrets, rate limiting, permissões.",
                "nivel": "Avançado",
                "palavras_chave": ["serverless", "Lambda", "função"],
            },
        ],
    },
    {
        "slug": "desenvolvimento-seguro-python",
        "titulo": "Desenvolvimento Seguro e Python para Segurança",
        "icone": "code",
        "descricao": "Práticas de desenvolvimento seguro (SSDLC), OWASP Secure Coding e Python para pentesting.",
        "ordem": 13,
        "objetivos": ["geral", "blue", "appsec"],
        "topicos": [
            {
                "slug": "ssdlc-secure-development",
                "titulo": "SSDLC: Ciclo de Vida de Desenvolvimento Seguro",
                "descricao": "Integre segurança em cada fase: design, implementação, teste, deploy e manutenção.",
                "nivel": "Intermediário",
                "palavras_chave": ["SSDLC", "segurança", "ciclo"],
            },
            {
                "slug": "code-review-static-analysis",
                "titulo": "Code Review e Análise Estática",
                "descricao": "Realize code reviews eficazes e use ferramentas SAST para encontrar vulnerabilidades.",
                "nivel": "Intermediário",
                "palavras_chave": ["review", "SAST", "código"],
            },
            {
                "slug": "owasp-secure-coding-principios",
                "titulo": "OWASP Secure Coding: Princípios",
                "descricao": "Aprenda 10 princípios: validação input, autenticação, criptografia, logging etc.",
                "nivel": "Intermediário",
                "palavras_chave": ["OWASP", "princípio", "validação"],
            },
            {
                "slug": "python-seguranca-bibliotecas",
                "titulo": "Python para Segurança: Bibliotecas e Tools",
                "descricao": "Use bibliotecas Python (requests, paramiko, pwntools) para ferramentas de segurança.",
                "nivel": "Intermediário",
                "palavras_chave": ["requests", "paramiko", "pwntools"],
            },
            {
                "slug": "dast-teste-dinamico-seguranca",
                "titulo": "DAST: Teste Dinâmico de Segurança",
                "descricao": "Use ferramentas DAST (Burp, OWASP ZAP) para testar aplicações em execução.",
                "nivel": "Avançado",
                "palavras_chave": ["DAST", "Burp", "ZAP"],
            },
            {
                "slug": "automacao-pipeline-seguranca",
                "titulo": "Automação: Pipeline de Segurança em CI/CD",
                "descricao": "Integre verificações de segurança em CI/CD: SAST, DAST, dependências, compliance.",
                "nivel": "Avançado",
                "palavras_chave": ["CI/CD", "automação", "pipeline"],
            },
        ],
    },
    {
        "slug": "hardening-identidade",
        "titulo": "Hardening e Gestão de Identidade",
        "icone": "lock",
        "descricao": "Fortaleça sistemas, configure autenticação multi-fator e gerencie identidades centralmente.",
        "ordem": 14,
        "objetivos": ["geral", "blue"],
        "topicos": [
            {
                "slug": "hardening-os-baseline-security",
                "titulo": "Hardening de SO: Baseline de Segurança",
                "descricao": "Aplique CIS Benchmarks, desabilite serviços desnecessários, configure firewalls de host.",
                "nivel": "Intermediário",
                "palavras_chave": ["CIS", "benchmark", "baseline"],
            },
            {
                "slug": "autenticacao-multifator-mfa",
                "titulo": "Autenticação Multi-Fator (MFA)",
                "descricao": "Implemente MFA: TOTP, U2F, SMS; aumente segurança de contas com múltiplos fatores.",
                "nivel": "Intermediário",
                "palavras_chave": ["MFA", "TOTP", "fator"],
            },
            {
                "slug": "gestao-senhas-vault",
                "titulo": "Gestão de Senhas e Secrets Vault",
                "descricao": "Use gestores de senhas, vaults (HashiCorp Vault) e rotate credenciais regularmente.",
                "nivel": "Intermediário",
                "palavras_chave": ["vault", "senha", "rotação"],
            },
            {
                "slug": "sso-saml-openid",
                "titulo": "SSO: SAML e OpenID Connect",
                "descricao": "Configure Single Sign-On com SAML 2.0 e OpenID Connect para autenticação centralizada.",
                "nivel": "Avançado",
                "palavras_chave": ["SSO", "SAML", "OpenID"],
            },
            {
                "slug": "privileged-access-management-pam",
                "titulo": "Privileged Access Management (PAM)",
                "descricao": "Gerencie acesso privilegiado: just-in-time access, session recording, audit.",
                "nivel": "Avançado",
                "palavras_chave": ["PAM", "privilegiado", "auditoria"],
            },
            {
                "slug": "zero-trust-modelo-seguranca",
                "titulo": "Zero Trust: Modelo de Segurança",
                "descricao": "Adopte paradigma zero trust: nunca confie, sempre verifique, segmentação de rede.",
                "nivel": "Avançado",
                "palavras_chave": ["zero trust", "verificação", "segmentação"],
            },
        ],
    },
]

RESERVA = {
    "fundamentos-redes": [
        {
            "tipo": "multipla",
            "topico": "modelo-osi-tcpip",
            "enunciado": "No HTTPS, o TLS roda sobre qual protocolo de transporte?",
            "alternativas": [
                "UDP",
                "TCP",
                "ICMP",
                "ARP",
            ],
            "correta": 1,
            "explicacao": "O HTTPS clássico é HTTP sobre TLS sobre TCP (porta 443). O TLS fica entre a aplicação e o transporte; no modelo OSI costuma ser associado às camadas 5/6. (O HTTP/3 usa QUIC, sobre UDP.)",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "enderecamento-ip",
            "enunciado": "Quantos endereços IP usáveis existem em uma rede /28?",
            "alternativas": ["2", "6", "14", "30"],
            "correta": 2,
            "explicacao": "Uma /28 tem 16 endereços totais (2^4). Subtraindo rede e broadcast, restam 14 usáveis.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "protocolo-tcp-udp",
            "enunciado": "TCP garante entrega ordenada de pacotes, enquanto UDP é um protocolo sem conexão.",
            "resposta": True,
            "explicacao": "Correto. TCP é orientado a conexão e entrega ordenada; UDP é sem conexão e não garante ordem.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "dns-http-https",
            "enunciado": "HTTPS usa porta 443 e criptografa a comunicação entre cliente e servidor com TLS.",
            "resposta": True,
            "explicacao": "Correto. HTTPS (porta 443) encapsula HTTP em TLS para comunicação segura.",
            "xp": 5,
        },
    ],
    "linux-seguranca": [
        {
            "tipo": "multipla",
            "topico": "permissoes-usuarios-grupos",
            "enunciado": "Qual comando altera permissões de arquivo para 755 (rwxr-xr-x)?",
            "alternativas": ["chown 755 arquivo", "chmod 755 arquivo", "chgrp 755 arquivo", "sudo chmod a+x arquivo"],
            "correta": 1,
            "explicacao": "chmod (change mode) altera permissões. 755 = rwxr-xr-x (proprietário rwx, grupo rx, outros rx).",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "shell-bash-scripting",
            "enunciado": "Em Bash, qual variável contém o número de argumentos passados a um script?",
            "alternativas": ["$#", "$*", "$@", "$$"],
            "correta": 0,
            "explicacao": "$# fornece o número de argumentos; $* expande todos; $@ expande como lista; $$ é PID do shell.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "processos-servicos-systemd",
            "enunciado": "systemd é o gerenciador de serviços padrão em distribuições Linux modernas.",
            "resposta": True,
            "explicacao": "Correto. systemd substituiu init em distribuições como Ubuntu, CentOS, Fedora.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "auditoria-logs-linux",
            "enunciado": "auditd registra eventos de segurança do kernel e está disponível em todos os sistemas Linux por padrão.",
            "resposta": False,
            "explicacao": "auditd é uma ferramenta robusta de auditoria, mas não é instalada por padrão; deve ser configurada.",
            "xp": 5,
        },
    ],
    "windows-active-directory": [
        {
            "tipo": "multipla",
            "topico": "active-directory-conceitos",
            "enunciado": "Qual contêiner do Active Directory organiza usuários e computadores dentro de um domínio e permite delegar administração e vincular GPOs?",
            "alternativas": ["Floresta", "Árvore", "OU (Organizational Unit)", "Domínio"],
            "correta": 2,
            "explicacao": "OUs (Organizational Units) agrupam objetos dentro de um domínio; servem para delegar administração e vincular GPOs. Floresta, árvore e domínio são níveis maiores da hierarquia.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "autenticacao-kerberos",
            "enunciado": "Em Kerberos, o TGT (Ticket Granting Ticket) é obtido do serviço de autenticação (AS) e é válido por quanto tempo padrão?",
            "alternativas": ["1 hora", "8 horas", "10 horas", "30 dias"],
            "correta": 2,
            "explicacao": "Na política padrão de Kerberos do Active Directory, o TGT vale 10 horas e pode ser renovado por até 7 dias. Validade curta limita a janela de abuso de um ticket roubado.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "arquitetura-windows-seguranca",
            "enunciado": "UAC (User Account Control) impede que usuários não-administradores instalem software sem consentimento.",
            "resposta": True,
            "explicacao": "Correto. UAC promove para admin quando necessário; reduz danos de malware executado como usuário comum.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "grupo-politica-gpo",
            "enunciado": "Group Policy Objects (GPOs) são aplicadas apenas a usuários, nunca a computadores.",
            "resposta": False,
            "explicacao": "Falso. GPOs têm configurações de Computador e de Usuário e são vinculadas a sites, domínios ou OUs; grupos de segurança servem para filtrar quem recebe a política.",
            "xp": 5,
        },
    ],
    "criptografia": [
        {
            "tipo": "multipla",
            "topico": "simetrica-aes-des",
            "enunciado": "Qual destes NÃO é um tamanho de chave válido do AES?",
            "alternativas": ["128 bits", "192 bits", "256 bits", "512 bits"],
            "correta": 3,
            "explicacao": "O AES aceita chaves de 128, 192 ou 256 bits (o bloco é sempre de 128 bits). AES-128 segue seguro; AES-256 é preferido para dados de longo prazo.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "funcoes-hash-md5-sha",
            "enunciado": "Por que MD5 não deve ser usado para garantir integridade crítica?",
            "alternativas": [
                "É muito lento",
                "Produz hashes muito longos",
                "Colisões foram encontradas e exploradas",
                "Usa mais memória que SHA",
            ],
            "correta": 2,
            "explicacao": "Colisões práticas em MD5 foram encontradas; um atacante pode criar dois arquivos com mesmo MD5.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "asimetrica-rsa-ecc",
            "enunciado": "RSA de 3072 bits oferece segurança aproximadamente equivalente a uma chave simétrica de 128 bits (AES-128).",
            "resposta": True,
            "explicacao": "Correto. Pelo NIST SP 800-57: RSA-2048 ≈ 112 bits, RSA-3072 ≈ 128 bits e RSA-15360 ≈ 256 bits. ECC chega ao mesmo nível com chaves bem menores (P-256 ≈ 128 bits).",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "tls-ssl-seguranca-web",
            "enunciado": "Perfect Forward Secrecy (PFS) garante que a comprometimento de uma chave privada de longo prazo não compromete sessões antigas.",
            "resposta": True,
            "explicacao": "Correto. PFS usa chaves de sessão efêmeras; até mesmo com chave privada vazada, sessões antigas permanecem seguras.",
            "xp": 5,
        },
    ],
    "seguranca-web-owasp": [
        {
            "tipo": "multipla",
            "topico": "injecao-sql-xss",
            "enunciado": "Qual é a defesa mais eficaz contra injeção SQL?",
            "alternativas": [
                "Validar entrada com regex",
                "Usar prepared statements",
                "Escape de caracteres especiais",
                "Rejeitar todos caracteres não-alfanuméricos",
            ],
            "correta": 1,
            "explicacao": "Prepared statements separamtemplates SQL de dados; são imunes a injeção SQL.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "controle-acesso",
            "enunciado": "IDOR (Insecure Direct Object Reference) ocorre quando?",
            "alternativas": [
                "Um usuário acessa objetos de outro sem autorização",
                "Um objeto referencia diretamente outro em banco de dados",
                "Um usuário não pode acessar seu próprio objeto",
                "Um servidor usa IDs sequenciais para usuários",
            ],
            "correta": 0,
            "explicacao": "IDOR = falta de verificação de autorização ao acessar recursos. Exemplo: /user/123 sem verificar se 123 pertence ao usuário logado.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "autenticacao-sessao",
            "enunciado": "Cookies de sessão devem ter as flags HttpOnly e Secure para evitar roubo via XSS ou man-in-the-middle.",
            "resposta": True,
            "explicacao": "Correto. HttpOnly previne acesso por JS (XSS); Secure força HTTPS apenas.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "criptografia-dados-transito",
            "enunciado": "Criptografia em repouso protege os dados de um disco roubado, mas não substitui o TLS, que protege os dados em trânsito.",
            "resposta": True,
            "explicacao": "Correto. São camadas complementares: criptografia em repouso protege o armazenamento; TLS protege a comunicação na rede.",
            "xp": 5,
        },
    ],
    "seguranca-apis": [
        {
            "tipo": "multipla",
            "topico": "autenticacao-api-oauth-jwt",
            "enunciado": "JWT armazena informações sobre o usuário no próprio token. Por que não dever armazenar dados sensíveis (como senha)?",
            "alternativas": [
                "JWT não pode ser criptografado",
                "JWT é visível em plain text quando codificado em Base64",
                "JWT é sempre transmitido em plain text",
                "Tokens JWT podem ser roubados ou interceptados",
            ],
            "correta": 1,
            "explicacao": "JWT é Base64-encoded (não criptografado por padrão). Dados são legíveis; nunca coloque senhas, números de cartão etc.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "rate-limiting-throttling-api",
            "enunciado": "Qual é o principal benefício de implementar rate limiting em uma API?",
            "alternativas": [
                "Aumentar a velocidade de resposta",
                "Reduzir custos de computação",
                "Prevenir abuso, DoS e scrapers",
                "Melhorar a experiência do usuário legítimo",
            ],
            "correta": 2,
            "explicacao": "Rate limiting controla uso abusivo: ataque de força bruta, DoS, scraping não autorizado.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "validacao-esquema-api",
            "enunciado": "Uma API deve validar estritamente todas as entradas de usuário, mesmo campos 'não críticos' como comentários.",
            "resposta": True,
            "explicacao": "Correto. XSS, injeção e outros ataques podem ocorrer em qualquer campo; valide TUDO.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "documentacao-segura-api",
            "enunciado": "Documentação interativa de API (Swagger) deve ser sempre pública para facilitar integração.",
            "resposta": False,
            "explicacao": "Falso. Endpoints privados/internos não devem ser expostos publicamente; proteja documentação sensível.",
            "xp": 5,
        },
    ],
    "reconhecimento-osint": [
        {
            "tipo": "multipla",
            "topico": "osint-passive-information-gathering",
            "enunciado": "WHOIS query retorna qual tipo de informação sobre registro de domínio?",
            "alternativas": [
                "IP dos servidores web do domínio",
                "Registrante, data de registro, DNS primário",
                "Todas as páginas indexadas",
                "Histórico de visitantes do site",
            ],
            "correta": 1,
            "explicacao": "WHOIS contém: registrante, data criação/expiração, nameservers, contatos técnicos e administrativos.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "enumeracao-dns-subdominios",
            "enunciado": "Qual técnica de enumeração DNS descobre subdomínios testando um wordlist contra o DNS?",
            "alternativas": [
                "Zone transfer (AXFR)",
                "Brute force de subdomínios",
                "Análise de Certificate Transparency",
                "Google dorking",
            ],
            "correta": 1,
            "explicacao": "Brute force tenta subdomínios (api.example.com, mail.example.com) contra DNS; ferramentas: sublist3r, ffuf.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "vazamento-dados-breachdatabase",
            "enunciado": "Sites como HaveIBeenPwned permitem verificar se um email foi exposto em um vazamento de dados publicamente conhecido.",
            "resposta": True,
            "explicacao": "Correto. HIBP é ferramenta pública legítima de segurança; útil para verificar exposição de credenciais.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "framework-mitre-att-ck",
            "enunciado": "MITRE ATT&CK categoriza reconhecimento como uma tática de pré-exploração, antes do acesso inicial.",
            "resposta": True,
            "explicacao": "Correto. Reconhecimento é tática inicial; precede execution, persistence, etc.",
            "xp": 5,
        },
    ],
    "analise-vulnerabilidades-pentest": [
        {
            "tipo": "multipla",
            "topico": "metodologia-pentest-fases",
            "enunciado": "Qual é a primeira fase de um pentest profissional?",
            "alternativas": [
                "Exploração de vulnerabilidades",
                "Reconhecimento e coleta de informações",
                "Relatório final",
                "Pós-exploração e persistence",
            ],
            "correta": 1,
            "explicacao": "Depois do pré-engajamento (escopo e autorização por escrito), a primeira fase técnica é o reconhecimento: OSINT e mapeamento de ativos, antes de varredura ou exploração.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "classificacao-vulnerabilidades-cvss",
            "enunciado": "Uma vulnerabilidade com CVSS score 7.5 é classificada como?",
            "alternativas": ["Baixa", "Média", "Alta", "Crítica"],
            "correta": 2,
            "explicacao": "CVSS: 0.0-3.9 Baixa, 4.0-6.9 Média, 7.0-8.9 Alta, 9.0-10.0 Crítica. 7.5 = Alta.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "etica-pentest-acordo-legal",
            "enunciado": "Um pentest sem autorização escrita é ilegal e pode resultar em acusação de hacking não autorizado.",
            "resposta": True,
            "explicacao": "Correto. SEMPRE tenha contrato/ROE assinado; pentest sem permissão = crime.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "relatorio-pentest-comunicacao",
            "enunciado": "Um bom relatório de pentest deve incluir payloads completos de exploração para máxima clareza.",
            "resposta": False,
            "explicacao": "Falso. Relatórios devem descrever vulnerabilidades e remediação, não scripts prontos para ataque.",
            "xp": 5,
        },
    ],
    "blue-team-monitoramento-siem": [
        {
            "tipo": "multipla",
            "topico": "logs-centralizacao-siem",
            "enunciado": "Um SIEM ingere logs de múltiplas fontes e os normaliza. Por que normalização é importante?",
            "alternativas": [
                "Reduz tamanho dos arquivos de log",
                "Permite correlação consistente entre fontes diferentes",
                "Criptografa dados automaticamente",
                "Aumenta a velocidade de processamento",
            ],
            "correta": 1,
            "explicacao": "Normalização converte logs variados (Windows, Linux, firewall) para formato comum; essencial para correlação.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "regras-deteccao-alertas",
            "enunciado": "Um falso positivo em regras de detecção causa qual impacto?",
            "alternativas": [
                "Não causa impacto",
                "Cria alerta desnecessário; esgota SOC",
                "Aumenta segurança",
                "Reduz carga de trabalho",
            ],
            "correta": 1,
            "explicacao": "Falsos positivos causam alert fatigue; SOC ignora alertas reais. Tuning de regras é crítico.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "ips-ids-honeypot",
            "enunciado": "Um honeypot é um sistema decoy que imita serviços reais para detectar e desacelerar atacantes.",
            "resposta": True,
            "explicacao": "Correto. Honeypots capturam TTPs de atacantes sem risco a sistemas produção.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "threat-intelligence-indicadores",
            "enunciado": "IoCs (Indicadores de Compromisso) incluem hashes de malware, IPs de C2 e domínios maliciosos.",
            "resposta": True,
            "explicacao": "Correto. IoCs são observáveis que indicam um ataque ou comprometimento; usados em detecção.",
            "xp": 5,
        },
    ],
    "resposta-incidentes-forense": [
        {
            "tipo": "multipla",
            "topico": "plano-resposta-incidentes",
            "enunciado": "Um Incident Response Plan deve definir?",
            "alternativas": [
                "Apenas papéis técnicos",
                "Papéis, escalação, comunicação, recuperação e testes",
                "Apenas ferramentas a usar",
                "Apenas contatos de polícia",
            ],
            "correta": 1,
            "explicacao": "IRP define: estrutura (papéis), escalação (quando ativar), comunicação (quem avisa), recuperação.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "forense-digital-coleta-evidencia",
            "enunciado": "Por que a cadeia de custódia é crucial em forense digital?",
            "alternativas": [
                "Acelera investigação",
                "Comprova integridade; admissível em corte legal",
                "Reduz custos",
                "Previne perda de dados",
            ],
            "correta": 1,
            "explicacao": "Cadeia de custódia documenta: quem coletou, quando, onde; evita questionamento de evidência em julgamento.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "deteccao-classificacao-incidente",
            "enunciado": "Incidentes de segurança devem ser classificados por severidade para priorizar resposta.",
            "resposta": True,
            "explicacao": "Correto. Classificação (crítico/alto/médio/baixo) orienta alocação de recursos e tempo de resposta.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "lissoes-aprendidas-mejora",
            "enunciado": "Post-mortem de incidente não é necessário se o incidente foi resolvido rapidamente.",
            "resposta": False,
            "explicacao": "Falso. Post-mortem é essencial sempre; análise de root cause e lições aprendidas melhoram defesa.",
            "xp": 5,
        },
    ],
    "analise-malware": [
        {
            "tipo": "multipla",
            "topico": "tipos-malware-virus-worm-trojan",
            "enunciado": "Qual diferença fundamental entre um worm e um vírus?",
            "alternativas": [
                "Worm causa mais dano",
                "Worm se propaga automaticamente; vírus precisa de ação do usuário",
                "Vírus não usa rede",
                "São sinônimos",
            ],
            "correta": 1,
            "explicacao": "Worm se replica automaticamente pela rede; vírus requer execução/ação do usuário para se propagar.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "ofuscacao-packers-criptografia",
            "enunciado": "Um packer de malware?",
            "alternativas": [
                "Armazena o código malicioso em ZIP",
                "Compacta e criptografa código; desempacota em tempo de execução",
                "Remove funcionalidades desnecessárias",
                "Adiciona plugins maliciosos",
            ],
            "correta": 1,
            "explicacao": "Packers compactam e criptografam malware; desempacolam na memória para evitar detecção estática.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "analise-dinamica-estatica",
            "enunciado": "Análise estática examina o código malware sem executá-lo; análise dinâmica observa comportamento em sandbox.",
            "resposta": True,
            "explicacao": "Correto. Estática: desassembly, strings; dinâmica: APIs chamadas, arquivos criados, conexões de rede.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "apt-persist-c2-comunicacao",
            "enunciado": "Persistência em APT significa manter acesso mesmo após reboot ou limpeza inicial.",
            "resposta": True,
            "explicacao": "Correto. Persistência: backdoors, scheduled tasks, modificação de boot; crítica em ataques dirigidos.",
            "xp": 5,
        },
    ],
    "cloud-containers": [
        {
            "tipo": "multipla",
            "topico": "cloud-modelos-responsabilidade",
            "enunciado": "Em uma solução SaaS, quem é responsável por aplicação de patches de segurança?",
            "alternativas": ["Cliente", "Provedor de nuvem", "Ambos", "Ninguém obrigadamente"],
            "correta": 1,
            "explicacao": "SaaS: provedor gerencia tudo (SO, app, patches). Cliente responsável apenas por dados e credenciais.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "identidade-acesso-cloud-iam",
            "enunciado": "Princípio de least privilege em IAM significa?",
            "alternativas": [
                "Dar acesso total para facilitar trabalho",
                "Conceder permissões mínimas necessárias para função",
                "Ninguém recebe permissão",
                "Todos recebem permissão igual",
            ],
            "correta": 1,
            "explicacao": "Least privilege = permissões mínimas; reduz dano de comprometimento de conta.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "seguranca-armazenamento-cloud",
            "enunciado": "Buckets S3 devem ser configurados com acesso público ('public-read') apenas quando armazenam dados não-sensíveis.",
            "resposta": False,
            "explicacao": "Falso. Buckets S3 devem ser privados por padrão; poucas exceções e uso de pre-signed URLs para acesso.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "kubernetes-orquestracao-containers",
            "enunciado": "Kubernetes secrets devem ser criptografados em repouso e em trânsito dentro do cluster.",
            "resposta": True,
            "explicacao": "Correto. Secrets (certificados, senhas) devem ser criptografados; evita exposição em dumps de etcd.",
            "xp": 5,
        },
    ],
    "desenvolvimento-seguro-python": [
        {
            "tipo": "multipla",
            "topico": "ssdlc-secure-development",
            "enunciado": "SSDLC (Secure SDLC) é importante porque?",
            "alternativas": [
                "Apenas reduz custo",
                "Integra segurança desde design até pós-deploy; reduz bugs críticos",
                "Não muda segurança real",
                "É apenas marketing",
            ],
            "correta": 1,
            "explicacao": "SSDLC: threat modeling, code review, teste segurança, supply chain; previne vulnerabilidades caro em produção.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "owasp-secure-coding-principios",
            "enunciado": "Qual princípio OWASP Secure Coding é fundamental?",
            "alternativas": [
                "Validar TODAS as entradas de usuário",
                "Confiar em dados externos",
                "Hardcode senhas",
                "Usar algortimos frágeis",
            ],
            "correta": 0,
            "explicacao": "Validação: whitelist, reject invalid; primeira defesa contra injeção, XSS, buffer overflow.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "code-review-static-analysis",
            "enunciado": "SAST (Static Application Security Testing) analisa código-fonte sem executar para encontrar vulnerabilidades.",
            "resposta": True,
            "explicacao": "Correto. SAST: sonarqube, checkmarx; detecta padrões de risco em build time.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "automacao-pipeline-seguranca",
            "enunciado": "Um pipeline CI/CD pode integrar verificações de segurança que bloqueiam merge se houver vulnerabilidade crítica.",
            "resposta": True,
            "explicacao": "Correto. Gating: SAST/DAST devem passar antes de merge/deploy; previne código vulnerável.",
            "xp": 5,
        },
    ],
    "hardening-identidade": [
        {
            "tipo": "multipla",
            "topico": "hardening-os-baseline-security",
            "enunciado": "CIS Benchmark oferece?",
            "alternativas": [
                "Apenas recomendações opcionais",
                "Configurações mínimas de segurança auditáveis para SO",
                "Nenhuma orientação prática",
                "Recomendações de senha fraca",
            ],
            "correta": 1,
            "explicacao": "CIS Benchmarks: recomendações de hardening específicas por SO/aplicação; amplamente adotadas.",
            "xp": 10,
        },
        {
            "tipo": "multipla",
            "topico": "autenticacao-multifator-mfa",
            "enunciado": "TOTP (Time-based One-Time Password) gera códigos baseado em?",
            "alternativas": [
                "Sequência aleatória do servidor",
                "Horário atual (tempo Unix) + segredo compartilhado",
                "Biometria",
                "Localização do usuário",
            ],
            "correta": 1,
            "explicacao": "TOTP (RFC 6238) aplica HMAC sobre o segredo compartilhado e o tempo Unix em janelas de 30 s. Funciona offline, mas exige relógio sincronizado.",
            "xp": 10,
        },
        {
            "tipo": "vf",
            "topico": "gestao-senhas-vault",
            "enunciado": "Gestores de senhas (1Password, Bitwarden) armazenam senhas em nuvem criptografadas, sem acesso ao provedor.",
            "resposta": True,
            "explicacao": "Correto. Criptografia client-side; provedor não acessa senhas; busca segura por senha.",
            "xp": 5,
        },
        {
            "tipo": "vf",
            "topico": "zero-trust-modelo-seguranca",
            "enunciado": "Zero Trust assume que qualquer acesso, interno ou externo, deve ser verificado (autenticado, autorizado).",
            "resposta": True,
            "explicacao": "Correto. Zero Trust: nunca confie por padrão; MFA, micro-segmentação, monitoramento contínuo.",
            "xp": 5,
        },
    ],
}


def topico_por_slug(slug: str):
    """
    Retorna (modulo_dict, topico_dict) ou (None, None) se não encontrado.
    """
    for modulo in MODULOS:
        for topico in modulo["topicos"]:
            if topico["slug"] == slug:
                return (modulo, topico)
    return (None, None)


def topicos_ordenados(objetivo="geral"):
    """
    Retorna lista de tópicos ordenada:
    1. Módulos cujos 'objetivos' contêm o objetivo (mantendo ordem)
    2. Depois módulos demais
    Cada tópico no resultado inclui chave "modulo" com slug do módulo.
    """
    resultado = []

    # Primeiro: módulos com objetivo
    for modulo in MODULOS:
        if objetivo in modulo["objetivos"]:
            for topico in modulo["topicos"]:
                topico_com_modulo = topico.copy()
                topico_com_modulo["modulo"] = modulo["slug"]
                resultado.append(topico_com_modulo)

    # Depois: módulos sem objetivo (mantendo ordem)
    for modulo in MODULOS:
        if objetivo not in modulo["objetivos"]:
            for topico in modulo["topicos"]:
                topico_com_modulo = topico.copy()
                topico_com_modulo["modulo"] = modulo["slug"]
                resultado.append(topico_com_modulo)

    return resultado
